### ISSUE TITLE
[Lambo maker] Freezing balance numbers after a while (Win 10 x64)

### ISSUE THREAD

**Issue by amokmen** [cryply/cryply-miner#1]
After some working time, numbers just freeze and not changing. Only application restart could help to see actual numbers.

![cryply lambomaker_2018-04-05_23-17-22](https://user-images.githubusercontent.com/10855248/38389690-def16e80-3927-11e8-9239-5851e6127a2c.png)

**Comment by cryply** [comment]
This is old Cryply cli miner git
report this issue to Lambomager git
